# Generated by Django 3.2.5 on 2022-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('caption1', models.CharField(max_length=20)),
                ('caption2', models.CharField(max_length=20)),
                ('caption3', models.CharField(max_length=20)),
                ('caption4', models.CharField(max_length=20)),
                ('img1', models.ImageField(upload_to='projects-portfolio')),
                ('img2', models.ImageField(upload_to='projects-portfolio')),
                ('img3', models.ImageField(upload_to='projects-portfolio')),
                ('img4', models.ImageField(upload_to='projects-portfolio')),
            ],
        ),
    ]
